// BASIC SHADER FOR TESTING

#version 430 core
layout (local_size_x = 128) in; // workgroup scanline size
//note: 1024 minimum maximum guaranteed by opengl.

layout (rgba8, binding = 0) uniform image2D inImage;
layout (rgba8, binding = 1) uniform image2D outImage; 

void main()
{
	ivec2 curCoord = ivec2(gl_GlobalInvocationID.xy);
	vec4 inColor = imageLoad(inImage, curCoord).brga; //rotate color channels
	imageStore(outImage, curCoord, inColor);
}